import Head from "next/head";
import "bootstrap/dist/css/bootstrap.min.css";
import NavigationBar from "../components/NavigationBar";
import RegisterContact from "../components/RegisterContact";
import styles from "@/styles/Home.module.scss";

export default function AdicionarContato() {
  return (
    <>
      <Head>
        <title>Adicionar Contato</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <NavigationBar />
      </header>
      <main
        className={`${styles.main} container d-flex flex-column gap-3 col-6 justify-content-center align-items-center vh-100`}
      >
        <h5>Cadastrar contato</h5>
        <RegisterContact />
      </main>
    </>
  );
}
