import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import "bootstrap/dist/css/bootstrap.min.css";
import Find from "./components/find";
import ContactCard from "./components/ContactCard";
import RegistrationForm from "./components/registrationForm";

export default function Home() {
  return (
    <>
      <Head>
        <title>Phone Book</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container d-flex justify-content-center align-items-center vh-100">
        <div className="row w-100 gap-3 justify-content-center">
          <div className="card col-4 p-3">
            <h1 className={styles.title}>Cadastrar contato</h1>
            <RegistrationForm />
          </div>
          <div className={`${styles.contacts} card col-4 p-3 gap-2`}>
            <Find />
            <ContactCard />
          </div>
        </div>
      </main>
    </>
  );
}
